/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_postmeta` VALUES
(1,2,"_wp_page_template","default"),
(2,3,"_wp_page_template","default"),
(3,5,"_form","<label> Il tuo nome *\n    [text* your-name] </label>\n\n<label> La tua email *\n    [email* your-email] </label>\n\n<label> Il tuo telefono\n    [tel your-phone]</label>\n\n<label> Oggetto\n    [text your-subject] </label>\n\n<label> Il tuo messaggio *\n    [textarea* your-message] </label>\n\n[submit \"Invia\"]"),
(4,5,"_mail","a:9:{s:6:\"active\";b:1;s:7:\"subject\";s:34:\"serramentipiccolo \"[your-subject]\"\";s:6:\"sender\";s:53:\"serramentipiccolo <wordpress@serramentipiccolo.local>\";s:9:\"recipient\";s:26:\"luigipiccolo.lpl@gmail.com\";s:4:\"body\";s:229:\"Da: [your-name] <[your-email]>\nTelefono: [your-phone]\nOggetto: [your-subject]\n\nCorpo del messaggio:\n[your-message]\n\n-- \nQuesta e-mail è stata inviata da un modulo di contatto su serramentipiccolo (http://serramentipiccolo.local)\";s:18:\"additional_headers\";s:22:\"Reply-To: [your-email]\";s:11:\"attachments\";s:0:\"\";s:8:\"use_html\";b:0;s:13:\"exclude_blank\";b:0;}"),
(5,5,"_mail_2","a:9:{s:6:\"active\";b:0;s:7:\"subject\";s:34:\"serramentipiccolo \"[your-subject]\"\";s:6:\"sender\";s:53:\"serramentipiccolo <wordpress@serramentipiccolo.local>\";s:9:\"recipient\";s:12:\"[your-email]\";s:4:\"body\";s:150:\"Corpo del messaggio:\n[your-message]\n\n-- \nQuesta e-mail è stata inviata da un modulo di contatto su serramentipiccolo (http://serramentipiccolo.local)\";s:18:\"additional_headers\";s:36:\"Reply-To: luigipiccolo.lpl@gmail.com\";s:11:\"attachments\";s:0:\"\";s:8:\"use_html\";b:0;s:13:\"exclude_blank\";b:0;}"),
(6,5,"_messages","a:22:{s:12:\"mail_sent_ok\";s:46:\"Grazie per il tuo messaggio. È stato inviato.\";s:12:\"mail_sent_ng\";s:88:\"Si è verificato un errore durante l\'invio del tuo messaggio. Per favore prova di nuovo.\";s:16:\"validation_error\";s:69:\"Uno o più campi hanno errori. Per favore controlla e prova di nuovo.\";s:4:\"spam\";s:88:\"Si è verificato un errore durante l\'invio del tuo messaggio. Per favore prova di nuovo.\";s:12:\"accept_terms\";s:70:\"Devi accettare termini e condizioni prima di inviare il tuo messaggio.\";s:16:\"invalid_required\";s:22:\"Il campo è richiesto.\";s:16:\"invalid_too_long\";s:25:\"Il campo è troppo lungo.\";s:17:\"invalid_too_short\";s:25:\"Il campo è troppo corto.\";s:12:\"invalid_date\";s:38:\"Il formato della data non è corretto.\";s:14:\"date_too_early\";s:50:\"La data è antecedente alla prima data consentita.\";s:13:\"date_too_late\";s:49:\"La data è successiva all\'ultima data consentita.\";s:13:\"upload_failed\";s:71:\"Si è verificato un errore sconosciuto durante il caricamento del file.\";s:24:\"upload_file_type_invalid\";s:56:\"Non sei abilitato al caricamenti di file di questo tipo.\";s:21:\"upload_file_too_large\";s:25:\"Il file è troppo grande.\";s:23:\"upload_failed_php_error\";s:48:\"Si è verificato un errore nel caricare il file.\";s:14:\"invalid_number\";s:34:\"Il formato numerico non è valido.\";s:16:\"number_too_small\";s:44:\"Il numero è inferiore al minimo consentito.\";s:16:\"number_too_large\";s:45:\"Il numero è superiore al massimo consentito.\";s:23:\"quiz_answer_not_correct\";s:36:\"La risposta al quiz non è corretta.\";s:13:\"invalid_email\";s:41:\"L\'indirizzo email inserito non è valido.\";s:11:\"invalid_url\";s:20:\"L\'URL non è valido.\";s:11:\"invalid_tel\";s:36:\"Il numero di telefono non è valido.\";}"),
(7,5,"_additional_settings",""),
(8,5,"_locale","it_IT"),
(9,2,"_edit_lock","1590744432:1"),
(10,2,"_edit_last","1"),
(11,2,"_wp_trash_meta_status","publish"),
(12,2,"_wp_trash_meta_time","1590745235"),
(13,2,"_wp_desired_post_slug","homepage");
